### ISSUE TITLE
Some mob spawners will revert to original mob type after modification

### ISSUE THREAD

**Issue by totrider** [katanya04/mine-spawners#1]
I am using another mod to optain spawn eggs in survival. I have been running into this random issue where some spawners, will revert back and spawn their original mob type. I did a bit of digging, and I suspect this issue might be this old feature that some dungeon makers are still using. For reference, the modpack I am using, includes a few vanilla-like dungeon mods. The spawners I have specifically had issues with, are the endermite spawners fro BetterEnd.

https://github.com/Ellpeck/ActuallyAdditions/issues/162

As stated:

"This is all vanilla mechanics. If spawn potentials exist then the spawner will replace the "spawn data" contents with one of the "spawn potentials". if you don't wipe the spawn potentials then replacing the "spawn data" doesn't last longer than a single spawn cycle.

Just for clarity i added a snip from nbtexplorer to show what the nbt structure looks like."
![image](https://github.com/Marco2124/mine-spawners/assets/1184655/1575cf33-e6b4-4995-a5b9-9389851769a7)

"Wait, so are the spawn potentials the weird variable in the spawner logic that's called something with Minecart?
If so, should I just wipe that list when changing the spawner?"

"Yes, SpawnPotentials = WeightedMinecart. It's the stupidest translation I've ever seen in the mcp code base. What they really are is a list of possible things that may be spawned whenever a spawner pulses. They're selected by random weight. so you could have a spawner that has a 1/10 chance to spawn a creeper or something."

"Yea, I just made it wipe the entire list.
And yes, I made it write to nbt, deleted the tag the list is saving on, and then made it read from NBT.
Because without ASM hacking or reflection, I can't actually access the list :v"

**Comment by totrider** [comment]
Obviously, that post is from several years ago now, but I guess it is possible it is either a similar, if not the same issue.

**Comment by katanya04** [comment]
I'll look into this as soon as I can, thank you for telling me about this :)

**Comment by katanya04** [comment]
Wiping the SpawnPotentials data doesn't seem the solution: when the spawners spawns an entitiy, it sets the next spawn entity as some entity of the spawn potentials, if the spawn potentials are empty it will clear the spawn, no entity will spawn from it. So what I did was a mixin that modifies a function called on the action of using a spawn egg on a spawner, making it so the spawn potentials are set to have the entity from the spawn egg and nothing more. I have not tested it with that mod you were using... may do it in the future, but if you can now, please tell me if it works! :)

(Should be already downloadable at Modrinth, version 1.1.1)

**Comment by katanya04** [comment]
Closed due to lack of activity and that... I tried searching for one of those spawners from BetterEnd and couldn't find any in-game, so uh, I will suppose it's fixed since version 1.1.1 (but yeah, I didn't test it)
