### ISSUE TITLE
Feature Request: Add Chance When Breaking Spawner

### ISSUE THREAD

**Issue by Hakuati** [katanya04/mine-spawners#3]
Hey, the mod is good, but could you add a configuration option to set the chance when trying to break a spawner? I personally find 100% to be overpowered.

I Use the Fabric 1.21 Version.

Best Regards

**Comment by katanya04** [comment]
Added on release v1.4.2.
A config file `minespawners-config.json` will get created when starting minecraft on the config folder of Minecraft. You may also create it yourself.
It's a json that should have 1 entry, `"DROP_CHANCE"`, with a value of a float that can range from 0.0 (never drops) to 100.0 (always drops).
By default it will be set on 100.0 when creating the file if it doesn't exist.
The value can be set in-game using modmenu, on the mods config. Changing it that way will automatically update the value when pressing "done" (only if it's a correct value, that is from 0.0 to 100.0).
Without modmenu, you have to change it in the file and then reset minecraft
