### ISSUE TITLE
The "Delay" tag should be removed when copying over NBT from the spawner to the drop

### ISSUE THREAD

**Issue by arcade-smasher** [katanya04/mine-spawners#4]
When the code copies the NBT of the block onto the item drop, the "Delay" tag should be removed, as it represents how many ticks until next spawn, and it is usually different for each spawner, which in turn prevents spawners from being stacked.

**Comment by katanya04** [comment]
You are correct, I had also noticed this but wasn't sure whether to change it or not, but yeah i guess it is a bit stupid to keep it, i'll remove the tag.

**Comment by katanya04** [comment]
Fixed in v1.4.5 just released. Thank you :)
